### ISSUE TITLE
"There is no item named 'oppo_metadata' in the archive" Realme 3 pro RMX1851EX_11_OTA_1180_all_w236tl6xfsaL.ozip

### ISSUE THREAD

**Issue by 007shubhchaudhary** [bkerler/oppo_ozip_decrypt#82]
ozipdecrypt 1.32 (c) B.Kerler 2017-2022
"There is no item named 'oppo_metadata' in the archive"
Detected mode 2....
Finding key...  realme.ozip
Unknown mode2, boot.img wasn't encrypted
Extracting...  realme.ozip
Traceback (most recent call last):
  File "C:\Users\Shubham Chaudhary\Downloads\oppo_ozip_decrypt-master\oppo_ozip_decrypt-master\ozipdecrypt.py", line 258, in main
    if zo.extract('oppo_metadata', outpath):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1628, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1667, in _extract_member
    member = self.getinfo(member)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'oppo_metadata' in the archive"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shubham Chaudhary\Downloads\oppo_ozip_decrypt-master\oppo_ozip_decrypt-master\ozipdecrypt.py", line 318, in <module>    sys.exit(main(args.filename))
  File "C:\Users\Shubham Chaudhary\Downloads\oppo_ozip_decrypt-master\oppo_ozip_decrypt-master\ozipdecrypt.py", line 265, in main
    return mode2(filename)
  File "C:\Users\Shubham Chaudhary\Downloads\oppo_ozip_decrypt-master\oppo_ozip_decrypt-master\ozipdecrypt.py", line 208, in mode2
    os.remove(os.path.join(temp,"out"))
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Shubham Chaudhary\\Downloads\\oppo_ozip_decrypt-master\\oppo_ozip_decrypt-master\\temp\\out'

**Comment by TickledOnions** [comment]
I found a way to fix this error:
Use this fork https://github.com/wzsx150/oppo_ozip_decrypt
